### ISSUE TITLE
Multipier functionality

### ISSUE THREAD

**Issue by rperez89** [1Hive/payroll-app#22]
Research and first implementation about the multiplier.

**Comment by willjgriff** [comment]
Multiplier functionality for what? Can this be expanded on?

**Comment by rperez89** [comment]
> Is this referring to the multiplier functionality mentioned here: #2 ? In which case it should be pretty straight forward, if an individual has a salary amount in one currency, we just need to store a modifiable multiplier which is used when determining the equity amount when the user claims their salary.

yes is about that, but i also want to try to understand the rationale behind this. I am not full understanding this

**Comment by lkngtn** [comment]
> yes is about that, but i also want to try to understand the rationale behind this. I am not full understanding this

The reasoning for the multiplier is that the organization would use it to value their non-liquid or vested asset relative to the base asset. If you are opting to receive tokens/rep/equity instead of cash you are taking on an additional risk and making a bet on the future value of those assets being greater than cash. Depending on the level or risk the multiplier would need to be set higher in order to make the option attractive. 

Some related thoughts on that concept here that might be worth reviewing #20

**Comment by rperez89** [comment]
closed via #26
